version: '2'
services:
  dc1consul:
    image: consul:0.7.5
    command: 
      - "agent"
      - "-server"
      - "-client"
      - "0.0.0.0"
      - "-ui"
      - "-bind"
      - "0.0.0.0"
      - "-datacenter"
      - "dc1"
      - "-join-wan"
      - "172.25.2.101"
      - "-bootstrap"
    hostname: dc1consul
    networks:
      datacenter:
        ipv4_address: 172.25.0.101
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    restart: unless-stopped

  dc2consul:
    image: consul:0.7.5
    command:
      - "agent"
      - "-server"
      - "-client"
      - "0.0.0.0"
      - "-ui"
      - "-bind"
      - "0.0.0.0"
      - "-datacenter"
      - "dc2"
      - "-join-wan"
      - "172.25.0.101"
      - "-bootstrap"
    hostname: dc2consul
    networks:
      datacenter:
        ipv4_address: 172.25.2.101
    ports:
      - 18500:8500
      - 18600:8600/tcp
      - 18600:8600/udp
    restart: unless-stopped

  dc1db1:
    image: postgres:9-alpine
    hostname: dc1db1
    networks:
      - datacenter
    restart: unless-stopped

  dc1agent1:
    build:
      context: agent
    image: pg-consulagent:latest
    command:
      - "agent"
      - "-client"
      - "0.0.0.0"
      - "-bind"
      - "0.0.0.0"
      - "-join"
      - "172.25.0.101"
      - "-datacenter"
      - "dc1"
    links:
      - dc1db1:db
    hostname: dc1agent1
    networks:
      datacenter:
        ipv4_address: 172.25.0.151
    restart: unless-stopped

  dc1db2:
    image: postgres:9-alpine
    hostname: dc1db2
    networks:
      - datacenter
    restart: unless-stopped

  dc1agent2:
    build:
      context: agent
    image: pg-consulagent:latest
    command:
      - "agent"
      - "-client"
      - "0.0.0.0"
      - "-bind"
      - "0.0.0.0"
      - "-join"
      - "172.25.0.101"
      - "-datacenter"
      - "dc1"
    links:
      - dc1db2:db
    hostname: dc1agent2
    networks:
      datacenter:
        ipv4_address: 172.25.0.152
    restart: unless-stopped

  dc2db1:
    image: postgres:9-alpine
    hostname: dc2db1
    networks:
      - datacenter
    restart: unless-stopped

  dc2agent1:
    build:
      context: agent
    image: pg-consulagent:latest
    command:
      - "agent"
      - "-client"
      - "0.0.0.0"
      - "-bind"
      - "0.0.0.0"
      - "-join"
      - "172.25.2.101"
      - "-datacenter"
      - "dc2"
    links:
      - dc2db1:db
    hostname: dc2agent1
    networks:
      datacenter:
        ipv4_address: 172.25.2.201
    restart: unless-stopped

networks:
  datacenter:
    ipam:
        config:
        - subnet: 172.25.0.0/16
